Map Control Zom/Pan History
g3w-suite/g3w-client pull request #388
Opened 2023-03-21 14:09 UTC by volterra79

Closes: #387

Steps:

1. From G3W-ADMIN click on **tools icon** (top-right) 
![Screenshot from 2023-03-21 14-55-56](https://user-images.githubusercontent.com/1051694/226628204-3f0e26c0-e5df-46d5-aecd-ffe10faeae21.png)
and click on **Django Administration** item
![Screenshot from 2023-03-21 14-55-02](https://user-images.githubusercontent.com/1051694/226628006-5ba41380-f92e-4b42-9ac8-982bc0f48056.png)

2. Click on **Map controls** item 

![Screenshot from 2023-03-21 14-58-01](https://user-images.githubusercontent.com/1051694/226629099-024044c7-cbd2-4965-9b9c-54f9bdfe232f.png)

3. Click on **ADD MAP CONTROL**

![Screenshot from 2023-03-21 14-59-47](https://user-images.githubusercontent.com/1051694/226629449-d60c5329-ee82-4439-874a-3cb0430ed078.png)

4. Set _zoomhistory_ in name input and Save it

![Screenshot from 2023-03-21 15-01-02](https://user-images.githubusercontent.com/1051694/226630001-eee0dca7-ea82-449b-b2a9-6937d69592b8.png)

5.  Move it to the top and back to G3W-ADMIN

![Screenshot from 2023-03-21 15-06-26](https://user-images.githubusercontent.com/1051694/226631933-7327d3d0-bcf4-48bd-8163-79215f9e4859.png)

6. Go to Cartographic Group and chose a Group where add new map control

![Screenshot from 2023-03-21 15-02-48](https://user-images.githubusercontent.com/1051694/226630882-b3ad7536-634a-4c85-a9bc-68505f6d5eb2.png)

7. It will appear on G3W-ClIENT

![Screenshot from 2023-03-21 15-09-10](https://user-images.githubusercontent.com/1051694/226632406-e2dddb39-4ade-4e68-a614-3b1338700968.png)

2023-03-21 15:54 UTC, wlorenzetti commented
I'll open a new issue to add by default `zoomhistory` to g3w-admin.

2023-03-21 16:01 UTC, volterra79 commented
> I'll open a new issue to add by default `zoomhistory` to g3w-admin.

@wlorenzetti  Please add also _querybydrawpolygon_  as default map control https://github.com/g3w-suite/g3w-client/pull/341

2023-03-21 16:08 UTC, wlorenzetti commented
https://github.com/g3w-suite/g3w-admin/issues/486

2023-03-22 08:04 UTC, Raruto requested changes

2023-03-22 08:04 UTC, Raruto commented on src/components/MapControlZoomHistory.vue
> +      v-t-tooltip="'Back'"
**NB** other translations are still missing, 

Something like `"step back"` and `"step forward"` could be more appropriate?

2023-03-22 08:44 UTC, Raruto approved these changes

2023-03-22 09:36 UTC, Raruto approved these changes
Not a big fan of those arrow icons, but as a starting point it's fine

2023-03-22 09:38 UTC, volterra79 commented
> Not a big fan of those arrow icons, but as a starting point it's fine

@Raruto we can choose icons here https://fontawesome.com/v5/search?o=r&m=free

2023-03-22 10:13 UTC, Raruto commented
Perhaps setted as follows it might be more immediate to understand, but as i often say right now i don't know how much "rework" it might require..

![image](https://user-images.githubusercontent.com/9614886/226870118-7f1632da-6133-400a-96f6-b5d7dae5d5fa.png)

**Font awesome icons used:**

- [reply](https://fontawesome.com/v5/icons/reply?f=classic&s=solid)
- [share](https://fontawesome.com/v5/icons/share?f=classic&s=solid)

2023-03-22 15:01 UTC, Raruto commented
@volterra79 great job with https://github.com/g3w-suite/g3w-client/pull/388/commits/6a72558e94d192ff9ee6916ad3730097b59605a7 🎖️.

Feel free to merge it.

2023-03-30 09:14 UTC, merged